///Mercury-specific constants used throughout the Apex classes/triggerrs
public class Constants  {
    public static String DEALER = 'Dealer';
    public static String DEVELOPER = 'Developer';
    public static String PRIMARYLIAISON = 'Primary Liaison';
    public static string CRM_LINK = 'https://crm.mercurypay.com/';
    
    
    //Profile- RAAVI
    public static String SYSADMIN = 'System Administrator';
    public static String API = 'MPS-API';
    public static String ITDEVELOPER = 'MPS-IT Developer';
    
    
}