public class TestBean{
public String firstName;
public String lastName;
public String city;

public void setFirstName(String firstName){
this.firstName=firstName;
}
public void setLastName(String lastName){
this.lastName=lastName;
}
public void setCity(String city){
this.city=city;
}
public String getFirstName(){
return firstName;
}
public String getLastName(){
return lastName;
}
public String getCity(){
return city;
}
}